# Generated by Django 4.0.5 on 2022-06-10 02:05

from django.db import migrations


def populate_sections(apps, schemaeditor):
    sections = {
        "Headlines": "Top Stories of the day.",
        "Spider-Man": "News of the masked crusader.",
        "Sports": "Are there even sports in the spider verse?",
    }
    Section = apps.get_model('articles', 'Section')
    for name, desc in sections.items():
        sections_obj = Section(name=name, description=desc)
        sections_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sections),
    ]
