# Generated by Django 4.0.5 on 2022-06-10 00:41

from django.db import migrations

def populate_languages(apps, schemaeditor):
    languages = [
        {
            "key" : "EN",
            "name" : "English"
        },
        {
            "key" : "ES",
            "name" : "Spanish"
        },
        {
            "key" : "PT",
            "name" : "Portuguese"
        },
        {
            "key" : "DE",
            "name" : "German"
        },
    ]
    Language = apps.get_model('accounts', 'Language')
    for language in languages:
        lang_obj = Language(
            key=language.get("key"),
            name=language.get("name")
        )
        lang_obj.save()

def populate_roles(apps, schemaeditor):
    roles = {
        "reader": "A subscriber to the newspaper.",
        "jornalist": "A staff member that creates content.",
        "editor": "A staff member in charge of editing."
    }
    Role = apps.get_model('accounts', 'Role')
    for name, desc in roles.items():
        role_obj = Role(name=name, description=desc)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_languages),
        migrations.RunPython(populate_roles),
    ]
